# Generated by Django 4.2.7 on 2025-08-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at']},
        ),
    ]
